name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: rust:1.88.0-bookworm

    env:
      LIBCLANG_PATH: /usr/lib/x86_64-linux-gnu
      BINDGEN_EXTRA_CLANG_ARGS: "-I/usr/include"

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: apt-get update && apt-get install -y build-essential libclang-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose